### PR TITLE
Update CookieLogger.php

### PR DESCRIPTION
**Pull request by RomanApunts**
Drecated Doctrine ManagerRegistry in favor to use Doctrine\Persistence\ManagerRegistry

### CODE REVIEW

**Review by mwillecke — COMMENTED** [review]
I support this to be compatible with doctrine/doctrine-bundle 2.1.

**Review by crabnky — APPROVED** [review]
I think this is really needed.

**Review by oliverfehmel — APPROVED** [review]

**Comment by oliverfehmel** [comment]
I would really appreciate this, as current LTS of symfony (4.4.15) requires it. Thanks a lot!

**Review by BeatRoy — APPROVED** [review]

**Comment by jkabat** [comment]
@matthijsch any chance to merge it? Or would you like me to make changes to support both v1.3 and 2.0 at the same time?

**Review by matthijsch — APPROVED** [review]
👍

**Pull request merged**
